### ISSUE TITLE
1 Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by frannyfra** [gminova/gminova.github.io#1]
Failing Elements
--
<img class="img-profile" src="https://avatars3.githubusercontent.com/u/42014388?s=400&amp;u=3bbc8122dd44c4741c70f00c44b59bff84d38591&amp;v=4">
<img class="carousel-img" id="img" src="/img/pic1.jpg">
<img class="project-img" src="img/proj6.jpg">
<img class="project-img" src="img/proj7.jpg">
<img class="project-img" src="/img/proj1.jpg">
<img class="project-img" src="/img/proj4.jpg">
<img class="project-img" src="img/proj2.jpg">
<img class="project-img" src="img/proj3.jpg">
<img class="project-img" src="img/proj5.jpg">
<img class="project-img" src="img/proj9.jpg">
<img class="project-img" src="img/proj8.jpg">

**Comment by gminova** [comment]
fixed alt text added to images  
check-out commit 4ab6a56739524d2b568687823a1af8c6c91bdbc3
